# Generated by Django 3.0.5 on 2020-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerafeed', '0002_auto_20200410_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='license_number',
            field=models.CharField(max_length=10),
        ),
    ]
